package py.com.concepto.sysposto.dao.impl;

import org.springframework.stereotype.Repository;

import py.com.concepto.sysposto.dao.AnexoDao;
import py.com.concepto.sysposto.model.entity.Anexo;
import br.com.db1.myBatisPersistence.dao.GenericMyBatisDaoImpl;


/**
 * Implementação da <code>Interface</code> que define os métodos de acesso a dados Genéricos.
 * Define o nome do <code>Repository</code> que será criado no <code>Spring</code>.
 *
 * @author DB1 Informática - Generated by DB1 Eclipse Plugin
 *
 */
@Repository("anexoDao")
public class AnexoDaoImpl extends GenericMyBatisDaoImpl<Anexo, Long> implements AnexoDao {

	/**
	 * Construtor padrão da implementação do <code>Dao</code>.
	 */
	public AnexoDaoImpl() {
		super(Anexo.class); 
	}


}