package py.com.concepto.sysposto.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import py.com.concepto.sysposto.dao.UsuarioDao;
import py.com.concepto.sysposto.model.entity.Usuario;
import br.com.db1.myBatisPersistence.dao.GenericMyBatisDaoImpl;
import br.com.db1.myBatisPersistence.util.MyBatisUtil;


/**
 * Implementação da <code>Interface</code> que define os métodos de acesso a dados Genéricos.
 * Define o nome do <code>Repository</code> que será criado no <code>Spring</code>.
 *
 * @author DB1 Informática - Generated by DB1 Eclipse Plugin
 *
 */
@Repository("usuarioDao")
public class UsuarioDaoImpl extends GenericMyBatisDaoImpl<Usuario, Long> implements UsuarioDao {

	/**
	 * Construtor padrão da implementação do <code>Dao</code>.
	 */
	public UsuarioDaoImpl() {
		super(Usuario.class); 
	}
	
	/**
	 * pesquisa o usuario pelo login e senha usando na tela de autentificacao do sistema
	 */
	@Override
	@SuppressWarnings("unchecked")
	public Usuario findUsuarioByAutentificacao(String login, String senha) {
		List<Usuario> list = this.getSqlSession().selectList("findUsuarioByAutentificacao", MyBatisUtil.createMap("login", login, "senha", senha ));	
		Usuario usuario = new Usuario();	
		if(list.size() == 0){
			// usuario não encontrado com o login e senha informado
			usuario = new Usuario();
			usuario.setCodigo(-404L);
		}else{
			usuario = list.get(0);
		}
		return  usuario;			
	}

}