package py.com.concepto.sysposto.dao;

import br.com.db1.myBatisPersistence.dao.GenericMyBatisDao;


/**
 * Interface que define os métodos de acesso a dados Genéricos e que devem
 * ser customizados conforme a necessidade do <code>Model</code> que a implementa.
 *
 * @author DB1 Informática - Generated by DB1 Eclipse Plugin
 *
 */
public interface AnexoDao extends GenericMyBatisDao<py.com.concepto.sysposto.model.entity.Anexo, Long> {
}