package py.com.concepto.sysposto.service;

import py.com.concepto.sysposto.model.entity.Anexo;
import br.com.db1.myBatisPersistence.service.GenericMyBatisService;


/**
 * Interface que define os métodos de negócio Genéricos e que devem
 * ser customizados conforme a necessidade do <code>Model</code> que a implementa.
 *
 * @author DB1 Informática - Generated by DB1 Eclipse Plugin
 *
 */
public interface AnexoService extends GenericMyBatisService<Anexo, Long> {
	

}

